### ISSUE TITLE
A way to show individual US state stats

### ISSUE THREAD

**Issue by NoahJelen** [aatishb/covidtrends#14] opened 2020-03-29 04:31 UTC
Since the US is such a big country, is there a way to make the graph show the stats of individual states (ex: Arizona, Texas, California, etc.)?

**Comment by exclipy** [comment] 2020-03-29 14:02
This is a dupe of issue #5 .  See the demo of my PR #13 at https://exclipy.github.io/covidtrends/

**Comment by aatishb** [comment] 2020-04-05 03:38
closing as this is now live.

**Closed by aatishb** 2020-04-05 03:38 UTC
