### ISSUE TITLE
Relative scale by population

### ISSUE THREAD

**Issue by DjesonPV** [aatishb/covidtrends#220] opened 2021-01-20 16:03 UTC
Hi,
Can you make an option to plot the data by percentage of countries's population (divide the log and linear scale by the population of each country).
Because just plotting absolutes cases don't correlate the density of the spread, where relative cases in addition to the log scale would show the "real" state of the pandemic.

Regards

**Comment by shaal** [comment] 2021-01-25 19:28
Yes please!
That feature would be extremely helpful.

It seems that PR #94 is adding this functionality, and issue #214 link other similar requests.
In the above PR I found a working demo - https://covidtrends.eu-gb.mybluemix.net/

**Comment by FranklinYu** [comment] 2021-02-01 04:49
I recommend that this issue be closed as a duplicate of #30, which contains most of the debates.

**Closed as completed** 2021-02-24 15:23 UTC
